### ISSUE TITLE
Make test suite generic over the VM implementation

### ISSUE THREAD

**Issue by krl** [ComposableFi/cosmwasm-vm#23]
At the moment, only one implementation of the `WasmiVM` is being tested, since it is the only impl of `VMBase` at the moment this makes sense.

However to expand the tests to future more performant (JIT-compiled) `VMBase` implementors, we should make the tests be generic over `VMBase` as well

**Comment by blasrodri** [comment]
Additionally, once this is properly tested, we'd like to move to the more performant version in the runtime.
