### ISSUE TITLE
CosmWasm setup for research  team

### ISSUE THREAD

**Issue by dzmitry-lahoda** [ComposableFi/cosmwasm-vm#27]
# Description 

Researches need simple  script to run test with several contracts loaded and executed. They need ability to obtain output of tests run in release mode. 

# Solution

- document how to install proper version of rust and other dependencies if any (clang, protoc, wasm target etc)
- add several wasm contracts into repository
- add one tests which uploads, initializes and executes at least one instruction per contract with success
- provide bash command to run this test in release mode
- add trace level log output into `SimpleWasmiVM`  in memory usage methods (db_write, db_remove, db_read, etc) and other host functions. 
- provide simple bash command command to run test with all output showing access to storage from these contracts

# Acceptance

Researches use guide to setup their environment and run tests in described mode. Any help to follow guide is provided to them is provided on request via medium they prefer.

**Comment by dzmitry-lahoda** [comment]
@krl is it clear? should we have session to clarify?

**Comment by dzmitry-lahoda** [comment]
I suggest to split it into 2 PR. One is simple doc without too many tests and tracing details. And than with all tracing and more contracts. I am not expert in wasm, so my estimate is is 2 days to get this done. @krl are you ok with that? No nix, no CI, just simple local Rust and bash.

**Comment by dzmitry-lahoda** [comment]
https://github.com/ComposableFi/cosmwasm-vm/issues/28

**Comment by dzmitry-lahoda** [comment]
https://docs.google.com/document/d/1uWYEEVqxQGMGz0p2NqFdYIuFngBiP5STqog_FwL1O6I/edit?pli=1#

**Comment by dzmitry-lahoda** [comment]
https://docs.google.com/document/d/1uWYEEVqxQGMGz0p2NqFdYIuFngBiP5STqog_FwL1O6I/edit?pli=1&disco=AAAAwjhi4vI

**Comment by josietyleung** [comment]
@dzmitry-lahoda is this done and can we close? thanks
