### ISSUE TITLE
CosmWasm Research | storage layer intrumentation

### ISSUE THREAD

**Issue by blasrodri** [ComposableFi/cosmwasm-vm#28]
We'd need to provide the research team with a simple interface that they can use to instrument calls to the storage layer.

```rs
trait VMBase {

fn db_{read, write}()
}
```

should be used for this. Seems like the right place to do so is `SimpleWasmiVM` on `vm-wasmi/src/semantic.rs:L284`

I suggest to create an instrumentation layer that can be plugged there (or anywhere else). We could even extend `VMBase` for this (with a compilation target, only for these benchmarking purposes).

**Comment by dzmitry-lahoda** [comment]
closing as cosmos layers already instrumented.  enable all logs, kv logs.
