### ISSUE TITLE
Default `WasmLoader` fails to build

### ISSUE THREAD

**Issue by aeryz** [ComposableFi/cosmwasm-vm#6]
Previously, contracts were built with the following command by `WasmLoader`:
```
cargo build --release --target wasm32-unknown-unknown
```
But in the newer versions, `--lib` parameter needs to be present as well. 
So `WasmLoader` should use the following instead:
```
cargo build --lib --release --target wasm32-unknown-unknown
```

Actually most of the CosmWasm projects as well as the template projects provided by both us and CosmWasm make use of `wasm` alias. So I believe the best thing would be running `cargo wasm` by default so that it works regardless of the version.

**Comment by dzmitry-lahoda** [comment]
no sure we need it. we able to build and upload contracts and run the. reopen if fixes are needed.
