### ISSUE TITLE
Tracking issue for our `cosmwasm-std` PR

### ISSUE THREAD

**Issue by aeryz** [ComposableFi/cosmwasm-vm#7]
https://github.com/CosmWasm/cosmwasm/pull/1483

**Comment by hussein-aitlahcen** [comment]
@aeryz probably great to upgrade our patch to the latest cosmwasm-std version

**Comment by aeryz** [comment]
yeap, it seems like `1.2.0` is released.

**Comment by aeryz** [comment]
Updated to `1.2.0`

**Comment by dzmitry-lahoda** [comment]
September.
